#!/usr/bin/env python3
"""Agent OS 版本 manifest 生成器（P2-4）。

从 11 个 skill 的 _meta.json + SKILL.md frontmatter 自动生成
MANIFEST.yml（机器可读版本清单），避免人工 grep / 手工维护漂移。

用法：
    python3 scripts/gen_manifest.py [--write]   # --write 才落盘，默认打印预览
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
OUT = ROOT / "MANIFEST.yml"

AGENT_OS_VERSION = "1.3.0"
PROTOCOL_VERSION = "1.3"


def skill_version(skill_dir: Path) -> str:
    """优先 _meta.json 的 version，回退 SKILL.md frontmatter 的 version: X.Y.Z。"""
    meta = skill_dir / "_meta.json"
    if meta.exists():
        data = json.loads(meta.read_text(encoding="utf-8"))
        if data.get("version"):
            return data["version"]
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        m = re.search(r"^version:\s*([\w.]+)", skill_md.read_text(encoding="utf-8"), re.M)
        if m:
            return m.group(1)
    return "unknown"


def protocol_version(skill_dir: Path) -> str:
    """读取 SKILL.md frontmatter 的 metadata.agent_os.protocol_version。"""
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        m = re.search(r'protocol_version:\s*"?([\w.]+)"?', skill_md.read_text(encoding="utf-8"))
        if m:
            return m.group(1)
    return PROTOCOL_VERSION


def main() -> int:
    skills = []
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir() or not (skill_dir / "SKILL.md").exists():
            continue
        skills.append(
            {
                "name": skill_dir.name,
                "version": skill_version(skill_dir),
                "protocol_version": protocol_version(skill_dir),
            }
        )

    lines = [
        "# Agent OS Version Manifest (auto-generated by scripts/gen_manifest.py)",
        "# 不要手工编辑；改版本请改对应的 _meta.json / SKILL.md frontmatter 后重新生成。",
        "agent_os:",
        f"  version: {AGENT_OS_VERSION}",
        f"  protocol_version: {PROTOCOL_VERSION}",
        "  skills:",
    ]
    for s in skills:
        lines.append(
            f"    - name: {s['name']}\n      version: {s['version']}\n      protocol_version: {s['protocol_version']}"
        )
    content = "\n".join(lines) + "\n"

    if "--write" in sys.argv:
        OUT.write_text(content, encoding="utf-8")
        print(f"written: {OUT.relative_to(ROOT)} ({len(skills)} skills)")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())